// Code generated by entc, DO NOT EDIT.

package symptom

const (
	// Label holds the string label denoting the symptom type in the database.
	Label = "symptom"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldHpo holds the string denoting the hpo field in the database.
	FieldHpo = "hpo"
	// Table holds the table name of the symptom in the database.
	Table = "symptoms"
)

// Columns holds all SQL columns for symptom fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldHpo,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// HpoValidator is a validator for the "hpo" field. It is called by the builders before save.
	HpoValidator func(string) error
)
