// Code generated by entc, DO NOT EDIT.

package symptom

import (
	"entgo.io/ent/dialect/sql"
	"github.com/bjornaer/sympton-checker/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// Hpo applies equality check predicate on the "hpo" field. It's identical to HpoEQ.
func Hpo(v string) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldHpo), v))
	})
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldName), v))
	})
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Symptom {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Symptom(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldName), v...))
	})
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Symptom {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Symptom(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldName), v...))
	})
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldName), v))
	})
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldName), v))
	})
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldName), v))
	})
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldName), v))
	})
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldName), v))
	})
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldName), v))
	})
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldName), v))
	})
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldName), v))
	})
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldName), v))
	})
}

// HpoEQ applies the EQ predicate on the "hpo" field.
func HpoEQ(v string) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldHpo), v))
	})
}

// HpoNEQ applies the NEQ predicate on the "hpo" field.
func HpoNEQ(v string) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldHpo), v))
	})
}

// HpoIn applies the In predicate on the "hpo" field.
func HpoIn(vs ...string) predicate.Symptom {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Symptom(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldHpo), v...))
	})
}

// HpoNotIn applies the NotIn predicate on the "hpo" field.
func HpoNotIn(vs ...string) predicate.Symptom {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Symptom(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldHpo), v...))
	})
}

// HpoGT applies the GT predicate on the "hpo" field.
func HpoGT(v string) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldHpo), v))
	})
}

// HpoGTE applies the GTE predicate on the "hpo" field.
func HpoGTE(v string) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldHpo), v))
	})
}

// HpoLT applies the LT predicate on the "hpo" field.
func HpoLT(v string) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldHpo), v))
	})
}

// HpoLTE applies the LTE predicate on the "hpo" field.
func HpoLTE(v string) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldHpo), v))
	})
}

// HpoContains applies the Contains predicate on the "hpo" field.
func HpoContains(v string) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldHpo), v))
	})
}

// HpoHasPrefix applies the HasPrefix predicate on the "hpo" field.
func HpoHasPrefix(v string) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldHpo), v))
	})
}

// HpoHasSuffix applies the HasSuffix predicate on the "hpo" field.
func HpoHasSuffix(v string) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldHpo), v))
	})
}

// HpoEqualFold applies the EqualFold predicate on the "hpo" field.
func HpoEqualFold(v string) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldHpo), v))
	})
}

// HpoContainsFold applies the ContainsFold predicate on the "hpo" field.
func HpoContainsFold(v string) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldHpo), v))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Symptom) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Symptom) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Symptom) predicate.Symptom {
	return predicate.Symptom(func(s *sql.Selector) {
		p(s.Not())
	})
}
