version: '3'
services:
  symptom-checker:
    container_name: symptom-checker
    build: .
    ports: 
      - 8081:8081
    restart: on-failure
    networks:
      - ailment


  # symptom-checker-frontend:
  #   container_name: symptom-checker-frontend
  #   build: ./frontend/health
  #   environment:
  #     - REACT_APP_API=symptom-checker-backend:8081
  #   ports: 
  #     - 3000:80
  #   restart: on-failure
  #   depends_on:
  #     - symptom-checker-backend
  #   networks:
  #     - ailment
  #   volumes:
  #     - '.:/app'
  #     - '/app/node_modules'

# Networks to be created to facilitate communication between containers
networks:
  ailment:
    driver: bridge