version: '3'
services:
  backend:
    container_name: symptom-checker-backend
    build: .
    ports: 
      - 8081:8081
    restart: on-failure
    networks:
      - ailment


  frontend:
    container_name: symptom-checker-frontend
    build: ./frontend/health
    environment:
      - REACT_APP_API=backend:8081
    ports: 
      - 3000:3000
    restart: on-failure
    depends_on:
      - backend
    networks:
      - ailment
    volumes:
      - '.:/app'
      - '/app/node_modules'

# Networks to be created to facilitate communication between containers
networks:
  ailment:
    driver: bridge