// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AilmentsColumns holds the columns for the "ailments" table.
	AilmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Default: "unknown"},
		{Name: "symptoms", Type: field.TypeJSON},
		{Name: "hpos", Type: field.TypeJSON},
		{Name: "expert", Type: field.TypeString, Default: ""},
	}
	// AilmentsTable holds the schema information for the "ailments" table.
	AilmentsTable = &schema.Table{
		Name:       "ailments",
		Columns:    AilmentsColumns,
		PrimaryKey: []*schema.Column{AilmentsColumns[0]},
	}
	// SymptomsColumns holds the columns for the "symptoms" table.
	SymptomsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Default: "unknown"},
		{Name: "hpo", Type: field.TypeString, Unique: true},
	}
	// SymptomsTable holds the schema information for the "symptoms" table.
	SymptomsTable = &schema.Table{
		Name:       "symptoms",
		Columns:    SymptomsColumns,
		PrimaryKey: []*schema.Column{SymptomsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AilmentsTable,
		SymptomsTable,
	}
)

func init() {
}
