// Code generated by entc, DO NOT EDIT.

package ailment

import (
	"github.com/bjornaer/sympton-checker/ent/schema"
)

const (
	// Label holds the string label denoting the ailment type in the database.
	Label = "ailment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSymptoms holds the string denoting the symptoms field in the database.
	FieldSymptoms = "symptoms"
	// FieldHpos holds the string denoting the hpos field in the database.
	FieldHpos = "hpos"
	// Table holds the table name of the ailment in the database.
	Table = "ailments"
)

// Columns holds all SQL columns for ailment fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldSymptoms,
	FieldHpos,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// DefaultSymptoms holds the default value on creation for the "symptoms" field.
	DefaultSymptoms map[string]schema.SymptomDetails
	// DefaultHpos holds the default value on creation for the "hpos" field.
	DefaultHpos []string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)
