// Code generated by entc, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/bjornaer/sympton-checker/ent/ailment"
	"github.com/bjornaer/sympton-checker/ent/schema"
)

// Ailment is the model entity for the Ailment schema.
type Ailment struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Symptoms holds the value of the "symptoms" field.
	Symptoms map[string]schema.SymptomDetails `json:"symptoms,omitempty"`
	// Hpos holds the value of the "hpos" field.
	Hpos []string `json:"hpos,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Ailment) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case ailment.FieldSymptoms, ailment.FieldHpos:
			values[i] = new([]byte)
		case ailment.FieldID:
			values[i] = new(sql.NullInt64)
		case ailment.FieldName:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Ailment", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Ailment fields.
func (a *Ailment) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ailment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			a.ID = int(value.Int64)
		case ailment.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				a.Name = value.String
			}
		case ailment.FieldSymptoms:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field symptoms", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &a.Symptoms); err != nil {
					return fmt.Errorf("unmarshal field symptoms: %w", err)
				}
			}
		case ailment.FieldHpos:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field hpos", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &a.Hpos); err != nil {
					return fmt.Errorf("unmarshal field hpos: %w", err)
				}
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Ailment.
// Note that you need to call Ailment.Unwrap() before calling this method if this Ailment
// was returned from a transaction, and the transaction was committed or rolled back.
func (a *Ailment) Update() *AilmentUpdateOne {
	return (&AilmentClient{config: a.config}).UpdateOne(a)
}

// Unwrap unwraps the Ailment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (a *Ailment) Unwrap() *Ailment {
	tx, ok := a.config.driver.(*txDriver)
	if !ok {
		panic("ent: Ailment is not a transactional entity")
	}
	a.config.driver = tx.drv
	return a
}

// String implements the fmt.Stringer.
func (a *Ailment) String() string {
	var builder strings.Builder
	builder.WriteString("Ailment(")
	builder.WriteString(fmt.Sprintf("id=%v", a.ID))
	builder.WriteString(", name=")
	builder.WriteString(a.Name)
	builder.WriteString(", symptoms=")
	builder.WriteString(fmt.Sprintf("%v", a.Symptoms))
	builder.WriteString(", hpos=")
	builder.WriteString(fmt.Sprintf("%v", a.Hpos))
	builder.WriteByte(')')
	return builder.String()
}

// Ailments is a parsable slice of Ailment.
type Ailments []*Ailment

func (a Ailments) config(cfg config) {
	for _i := range a {
		a[_i].config = cfg
	}
}
