// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/bjornaer/sympton-checker/ent/symptom"
)

// Symptom is the model entity for the Symptom schema.
type Symptom struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Hpo holds the value of the "hpo" field.
	Hpo string `json:"hpo,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Symptom) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case symptom.FieldID:
			values[i] = new(sql.NullInt64)
		case symptom.FieldName, symptom.FieldHpo:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Symptom", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Symptom fields.
func (s *Symptom) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case symptom.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = int(value.Int64)
		case symptom.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				s.Name = value.String
			}
		case symptom.FieldHpo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hpo", values[i])
			} else if value.Valid {
				s.Hpo = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Symptom.
// Note that you need to call Symptom.Unwrap() before calling this method if this Symptom
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Symptom) Update() *SymptomUpdateOne {
	return (&SymptomClient{config: s.config}).UpdateOne(s)
}

// Unwrap unwraps the Symptom entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Symptom) Unwrap() *Symptom {
	tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Symptom is not a transactional entity")
	}
	s.config.driver = tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Symptom) String() string {
	var builder strings.Builder
	builder.WriteString("Symptom(")
	builder.WriteString(fmt.Sprintf("id=%v", s.ID))
	builder.WriteString(", name=")
	builder.WriteString(s.Name)
	builder.WriteString(", hpo=")
	builder.WriteString(s.Hpo)
	builder.WriteByte(')')
	return builder.String()
}

// Symptoms is a parsable slice of Symptom.
type Symptoms []*Symptom

func (s Symptoms) config(cfg config) {
	for _i := range s {
		s[_i].config = cfg
	}
}
