// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bjornaer/sympton-checker/ent/symptom"
)

// SymptomCreate is the builder for creating a Symptom entity.
type SymptomCreate struct {
	config
	mutation *SymptomMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (sc *SymptomCreate) SetName(s string) *SymptomCreate {
	sc.mutation.SetName(s)
	return sc
}

// SetNillableName sets the "name" field if the given value is not nil.
func (sc *SymptomCreate) SetNillableName(s *string) *SymptomCreate {
	if s != nil {
		sc.SetName(*s)
	}
	return sc
}

// SetHpo sets the "hpo" field.
func (sc *SymptomCreate) SetHpo(s string) *SymptomCreate {
	sc.mutation.SetHpo(s)
	return sc
}

// Mutation returns the SymptomMutation object of the builder.
func (sc *SymptomCreate) Mutation() *SymptomMutation {
	return sc.mutation
}

// Save creates the Symptom in the database.
func (sc *SymptomCreate) Save(ctx context.Context) (*Symptom, error) {
	var (
		err  error
		node *Symptom
	)
	sc.defaults()
	if len(sc.hooks) == 0 {
		if err = sc.check(); err != nil {
			return nil, err
		}
		node, err = sc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SymptomMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = sc.check(); err != nil {
				return nil, err
			}
			sc.mutation = mutation
			if node, err = sc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(sc.hooks) - 1; i >= 0; i-- {
			if sc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = sc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SymptomCreate) SaveX(ctx context.Context) *Symptom {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SymptomCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SymptomCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *SymptomCreate) defaults() {
	if _, ok := sc.mutation.Name(); !ok {
		v := symptom.DefaultName
		sc.mutation.SetName(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SymptomCreate) check() error {
	if _, ok := sc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Symptom.name"`)}
	}
	if _, ok := sc.mutation.Hpo(); !ok {
		return &ValidationError{Name: "hpo", err: errors.New(`ent: missing required field "Symptom.hpo"`)}
	}
	if v, ok := sc.mutation.Hpo(); ok {
		if err := symptom.HpoValidator(v); err != nil {
			return &ValidationError{Name: "hpo", err: fmt.Errorf(`ent: validator failed for field "Symptom.hpo": %w`, err)}
		}
	}
	return nil
}

func (sc *SymptomCreate) sqlSave(ctx context.Context) (*Symptom, error) {
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (sc *SymptomCreate) createSpec() (*Symptom, *sqlgraph.CreateSpec) {
	var (
		_node = &Symptom{config: sc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: symptom.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: symptom.FieldID,
			},
		}
	)
	if value, ok := sc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: symptom.FieldName,
		})
		_node.Name = value
	}
	if value, ok := sc.mutation.Hpo(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: symptom.FieldHpo,
		})
		_node.Hpo = value
	}
	return _node, _spec
}

// SymptomCreateBulk is the builder for creating many Symptom entities in bulk.
type SymptomCreateBulk struct {
	config
	builders []*SymptomCreate
}

// Save creates the Symptom entities in the database.
func (scb *SymptomCreateBulk) Save(ctx context.Context) ([]*Symptom, error) {
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Symptom, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SymptomMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SymptomCreateBulk) SaveX(ctx context.Context) []*Symptom {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SymptomCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SymptomCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
