// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Ailment is the predicate function for ailment builders.
type Ailment func(*sql.Selector)

// Symptom is the predicate function for symptom builders.
type Symptom func(*sql.Selector)
